export const content = {
  bg: {
    portfolioProject: 'ЛИЧЕН ПРОЕКТ',
    behindProject: 'Практика в разработката с AI',
    projectSummary:
      'Създадох този проект, за да развия уменията си за работа с AI: анализ на фотографии, координиране на специализирани агенти и проверка на техните решения. Процедурният модел се проверява с геометрични тестове, преглед в браузър и повторно зареждане на 3D експорта.',
    developer: 'Разработчик',
    builtWith: 'Технологии',
    visitPortfolio: 'Портфолио',
    viewCode: 'Код в GitHub',
    viewCaseStudy: 'Как използвах AI',
    tower: {
      eyebrow: 'ТЕЛЕВИЗИОННА КУЛА „СОФИЯ“',
      title: 'Над короните\nна дърветата.',
      description: '106 метра над парка. Част от София от 1959 г.',
    },
    name: 'Българска армия',
    brand: 'ДОМЪТ НА ЦСКА',
    location: 'Борисова градина, София',
    country: 'БЪЛГАРИЯ',
    collection: 'ЕДИН ОТБОР. ЕДИН ДОМ.',
    architectural: 'АРХИТЕКТУРНА РАЗХОДКА',
    explore: 'Открий стадиона',
    chapters: [
      'Общ изглед',
      'Трибуните',
      'Теренът',
      'Архитектура',
      'Борисова градина',
    ],
    eyebrows: [
      'НОВОТО НАЧАЛО',
      'СЪРЦЕТО НА СТАДИОНА',
      'БЛИЗО ДО ИГРАТА',
      'ВСЕКИ ДЕТАЙЛ ИМА ЗНАЧЕНИЕ',
      'ЕДНО МЯСТО. ПОКОЛЕНИЯ ИСТОРИЯ.',
    ],
    titles: [
      'Новият дом на ЦСКА.',
      'Червено сърце.\nЕдин глас.',
      'Тук започва\nследващата история.',
      'Архитектура\nс характер.',
      'В сърцето\nна София.',
    ],
    descriptions: [
      'Нашата история. Нашето бъдеще. Нашата Армия.',
      'Трибуни, създадени за общата ни страст.',
      'Всяка крачка към терена е крачка към мечтата.',
      'Златист силует. Открито небе. Нов хоризонт.',
      'Футболът и природата споделят един дом.',
    ],
    tour: 'Започни разходката',
    pause: 'Пауза',
    resume: 'Продължи',
    cutaway: 'Разрез',
    labels: 'Детайли',
    day: 'Ден',
    night: 'Вечер',
    capture: 'Снимка',
    export: 'Изтегли 3D модел',
    reset: 'Начален изглед',
    about: 'За проекта',
    fullscreen: 'Цял екран',
    exitFullscreen: 'Изход от цял екран',
    more: 'Още контроли',
    close: 'Затвори',
    save: 'Запази снимката',
    moment: 'Твоята Армия.',
    captureCaption: 'Изглед от твоята разходка.',
    loading: 'Създаваме твоя изглед',
    loadingSub: 'Борисова градина · София',
    hint: 'Плъзни, за да завъртиш',
    zoomHint: 'Скролирай за приближаване',
    mobileHint: 'Плъзни за завъртане · Щипни за мащаб',
    model: 'ВИЗУАЛИЗАЦИЯ ПО ФОТОГРАФИИ',
    free: 'СВОБОДЕН ИЗГЛЕД',
    number: 'ИЗГЛЕД',
    official: 'Официалният проект',
    aboutTitle: 'Дом за поколения.',
    aboutText:
      'Интерактивна архитектурна интерпретация на новия стадион „Българска армия“ — домът на ЦСКА в Борисовата градина.',
    accuracy:
      'Моделът е създаден по официални фотографии и визуализации. Геометрията и околният парк са приблизителни. Това не е геодезически модел или официален сайт на клуба.',
    credits:
      'Изображения и емблема: stadium.cska.bg / ЦСКА. Архитектурна визуализация и снимки от август 2026 г.',
    viewSource: 'Разгледай официалния проект',
    render: 'Архитектурна визуализация',
    photo: 'Официална фотография · август 2026',
    labelNames: [
      'Златистата фасада',
      'Покривна конструкция',
      'Трибуната на ЦСКА',
      'Теренът',
    ],
    failure: 'Стадионът, в цялата си красота.',
    failureText:
      '3D изгледът не е достъпен в този браузър. Разгледай официалната визуализация или опитай отново.',
    retry: 'Опитай 3D отново',
    exportBusy: 'Подготвяме модела…',
    exportDone: 'Моделът е готов.',
    exportError: 'Не успяхме да изтеглим модела. Опитай отново.',
    captureError: 'Снимката не е готова. Опитай отново.',
    fullscreenError: 'Целият екран не е достъпен в този браузър.',
    reduced: 'Намаленото движение е включено',
    tourUnavailable:
      'Автоматичната разходка е изключена при намалено движение.',
  },
  en: {
    portfolioProject: 'INDEPENDENT PROJECT',
    behindProject: 'Learning to build with AI',
    projectSummary:
      'I built this project to develop my AI-assisted engineering skills: interpreting photographs, coordinating specialist agents, and checking their decisions. The procedural model is verified through geometry tests, browser inspection, and 3D export re-import.',
    developer: 'Developer',
    builtWith: 'Built with',
    visitPortfolio: 'Visit my portfolio',
    viewCode: 'View source',
    viewCaseStudy: 'How I used AI',
    tower: {
      eyebrow: 'SOFIA TELEVISION TOWER',
      title: 'Above\nthe treetops.',
      description: '106 metres above the park. Part of Sofia since 1959.',
    },
    name: 'Bulgarian Army',
    brand: 'THE HOME OF CSKA',
    location: 'Borisova Gradina, Sofia',
    country: 'BULGARIA',
    collection: 'ONE TEAM. ONE HOME.',
    architectural: 'AN ARCHITECTURAL JOURNEY',
    explore: 'Explore the stadium',
    chapters: [
      'Overview',
      'The stands',
      'The pitch',
      'Architecture',
      'The park',
    ],
    eyebrows: [
      'A NEW BEGINNING',
      'THE HEART OF THE STADIUM',
      'CLOSER TO THE GAME',
      'EVERY DETAIL MATTERS',
      'ONE PLACE. GENERATIONS OF HISTORY.',
    ],
    titles: [
      'The new home of CSKA.',
      'A red heart.\nOne voice.',
      'Where the next\nstory begins.',
      'Architecture\nwith character.',
      'In the heart\nof Sofia.',
    ],
    descriptions: [
      'Our history. Our future. Our Army.',
      'Stands made for the passion we share.',
      'Every step towards the pitch is a step towards the dream.',
      'A golden silhouette. An open sky. A new horizon.',
      'Where football and nature share a home.',
    ],
    tour: 'Start the journey',
    pause: 'Pause tour',
    resume: 'Continue',
    cutaway: 'Cutaway',
    labels: 'Details',
    day: 'Daylight',
    night: 'Evening',
    capture: 'Capture',
    export: 'Download 3D model',
    reset: 'Reset view',
    about: 'About the project',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit fullscreen',
    more: 'More controls',
    close: 'Close',
    save: 'Save image',
    moment: 'Your stadium moment.',
    captureCaption: 'A view from your own journey.',
    loading: 'Preparing your view',
    loadingSub: 'Borisova Gradina · Sofia',
    hint: 'Drag to orbit',
    zoomHint: 'Scroll to zoom',
    mobileHint: 'Drag to orbit · Pinch to zoom',
    model: 'REFERENCE-BASED VISUALIZATION',
    free: 'ORBIT VIEW',
    number: 'VIEW',
    official: 'The official project',
    aboutTitle: 'A home for generations.',
    aboutText:
      'An interactive architectural interpretation of the new Bulgarian Army Stadium — the home of CSKA in Sofia’s Borisova Gradina park.',
    accuracy:
      'Created from official photographs and architectural visualizations. Stadium geometry and the surrounding park are approximate. This is not a surveyed model or an official club website.',
    credits:
      'Images and crest: stadium.cska.bg / CSKA. Architectural rendering and photographs from August 2026.',
    viewSource: 'Explore the official project',
    render: 'Architectural visualization',
    photo: 'Official photograph · August 2026',
    labelNames: [
      'The golden facade',
      'Roof structure',
      'The CSKA stand',
      'The pitch',
    ],
    failure: 'The stadium, in all its beauty.',
    failureText:
      'The 3D view is unavailable in this browser. Explore the official visualization or try again.',
    retry: 'Try 3D again',
    exportBusy: 'Preparing the model…',
    exportDone: 'Your model is ready.',
    exportError: 'The model could not be downloaded. Please try again.',
    captureError: 'Your image is not ready. Please try again.',
    fullscreenError: 'Fullscreen is unavailable in this browser.',
    reduced: 'Reduced motion is enabled',
    tourUnavailable: 'Automatic tours are disabled with reduced motion.',
  },
}
export type Copy = typeof content.bg
